name: env-pyvisco
channels:
  - default
  - conda-forge
dependencies:
  - python
  - matplotlib
  - numpy
  - pandas
  - scipy=1.8.1
  - ipykernel
  - ipython
  - ipywidgets>=8.0
  - xlrd
  - markdown
  - ipympl
  - voila
