name: env-pyvisco
channels:
  - default
  - conda-forge
dependencies:
  - python
  - matplotlib
  - numpy
  - pandas
  - scipy=1.8.1
  - ipykernel
  - ipython
  - ipywidgets=7.6.5
  - xlrd
  - markdown
  - ipympl
  - voila=0.3.6
